Fix @pytube/pytube #1222 #1225 #1222
pytube/pytube pull request #1230
Opened 2022-02-03 16:59 UTC by DEADF00D

The issue is on the regex of the `func_regex` of `parser.throttling_array_split()` and on the regex `function_patterns[0]` of `cipher.get_throttling_function_name()`  
Published an according fork for this fix.  
Succesfully tested, now in production on my app.

2022-02-03 19:11 UTC, rmwise reviewed
It works!

2022-02-04 02:36 UTC, antoninodimaggio commented
Works please merge!

2022-02-04 07:47 UTC, RONNCC commented
hey

thanks for the PR!

Can you add
- a unit test to show the behavior before and after
- some context on the need for the change 


Ideally this would 'break' in the future when youtube also changes behavior again and we can show it as a regression

2022-02-04 17:10 UTC, lerry30 commented
THANK YOU

2022-02-04 17:21 UTC, glubsy commented
This patch might work for now, but it assumes that the content of the throttling function does not change and starts with `var b = a.split("")`, and takes one argument `a`.

2022-02-05 01:54 UTC, DEADF00D commented
@glubsy If it's a need I can adapt the regex.

2022-02-05 09:58 UTC, Valenwe approved these changes
It works :)
good job!

2022-02-05 11:30 UTC, lerry30 commented
Another error

Exception in Tkinter callback
Traceback (most recent call last):
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
File "c:\Users\me\Desktop\python\main.py", line 51,
    YouTube(clip).streams.get_highest_resolution()
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\__main__.py", line 71, in __init__
    self.video_id = extract.video_id(url)
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\extract.py", line 133, in video_id
    return regex_search(r"(?:v=|\/)([0-9A-Za-z_-]{11}).*", url, group=1)
File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\site-packages\pytube\helpers.py", line 129, in regex_search
    raise RegexMatchError(caller="regex_search", pattern=pattern)
pytube.exceptions.RegexMatchError: regex_search: could not find match for (?:v=|\/)([0-9A-Za-z_-]{11}).*

2022-02-05 12:25 UTC, DEADF00D commented
@lerry30 can you provide vidéo url ?

2022-02-05 17:50 UTC, aryamaddel requested changes
these changes resolved the issue "NoneType' object has no attribute 'span'"

2022-02-05 23:31 UTC, lerry30 commented
> @lerry30 can you provide vidéo url ?

At first it worked when I tried your solution, but now it doesn't work any video on yt I'll try to download.

2022-02-06 00:01 UTC, lerry30 commented
@DEADF00D I'm sorry, there was an error in my code and I found it, now it's working again.

2022-02-06 12:45 UTC, nabinbhusal80 commented
Just replace in `cipher.py` and it works
`
function_patterns = [
        # https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377
        # a.C&&(b=a.get("n"))&&(b=Dea(b),a.set("n",b))}};
        # In above case, `Dea` is the relevant function name
        # r'a\.[A-Z]&&\(b=a\.get\("n"\)\)&&\(b=([^(]+)\(b\)', // (old one)
        r'([A-Za-z]{3})=function\(a\){var b=a\.split\(""\)\,'
    ]
`

2022-02-07 05:08 UTC, boardkeystown commented
LETS GOOOOO!!!! 


I don't know why but I can confirm that that those 2 changes worked.


Can someone explain to me what is going on with these regexs in parser and in cipher? 

func_regex = re.compile(r"function\(.*?\)")
r'([A-Za-z]{3})=function\(a\){var b=a\.split\(""\)\,'


I simply do not understand how what it is they are really looking for in YT. If I knew better maybe I could help out when YT changes whatever it is they change.

2022-02-08 18:50 UTC, R-Olivaw commented
@DEADF00D This works! Thank you!!

2022-02-09 05:26 UTC, Pinheiro-Lucas commented
It works, ty =)

2022-02-09 08:30 UTC, RONNCC commented
@DEADF00D  can you add a unit test

2022-02-09 11:44 UTC, DEADF00D commented
Yep ! I'll find time by the end of the week.

Le mer. 9 févr. 2022, 9:30 AM, Ronnie Ghose ***@***.***> a
écrit :

> @DEADF00D <https://github.com/DEADF00D> can you add a unit test
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pytube/pytube/pull/1230#issuecomment-1033484663>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKEMHCQA7RQNQG5BE3XSB23U2IQ23ANCNFSM5NPPOBXA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-09 15:19 UTC, DEADF00D commented
@RONNCC 

What do you mean by showing "the behavior before and after" ?
I mean, does the current unit test not enough to test this version ?

2022-02-10 07:11 UTC, dterg commented
This still doesn't work for me:
`  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\__main__.py", line 292, in streams
    return StreamQuery(self.fmt_streams)
  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\__main__.py", line 177, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\cipher.py", line 43, in __init__
    self.throttling_plan = get_throttling_plan(js)
  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\cipher.py", line 387, in get_throttling_plan
    raw_code = get_throttling_function_code(js)
  File "C:\Users\usr\anaconda3\envs\protist\lib\site-packages\pytube\cipher.py", line 301, in get_throttling_function_code
    code_lines_list = find_object_from_startpoint(js, match.span()[1]).split('\n')
AttributeError: 'NoneType' object has no attribute 'span'`

2022-02-10 12:11 UTC, DEADF00D commented
@dterg Still works on my side.
Did you patched it yourself or cloned it from my fork ?

2022-02-10 19:07 UTC, dterg commented
> @dterg Still works on my side. Did you patched it yourself or cloned it from my fork ?

@DEADF00D I can confirm your fork works. My error above was if this PR/code changes are merged onto current pip version

2022-02-14 13:23 UTC, closed without merging

2022-02-14 18:50 UTC, traceUserX reviewed
Worked for me