Update cipher.py
pytube/pytube pull request #1244
Opened 2022-02-08 11:21 UTC by ifahadone

resolved these #1243 #1240 #1233 #1228 #1225 #1218 , as of 2022-02-08

2022-02-09 12:13 UTC, Bryan-Roger approved these changes

2022-02-11 08:31 UTC, vishnudas-bluefox approved these changes

2022-02-12 14:13 UTC, Panos-Jr commented
Excellent!

2022-02-12 16:44 UTC, glubsy requested changes
You need to add proper unit tests.

2022-02-12 16:44 UTC, glubsy commented on pytube/cipher.py
> +            is_Array = True if '[' or ']' in function_name else False
This is wrong, as pointed out by [this comment](https://github.com/pytube/pytube/issues/1243#issuecomment-1037010471).

2022-02-12 16:50 UTC, glubsy commented on pytube/cipher.py
> +            is_Array = True if '[' or ']' in function_name else False
Also why make a variable out of it?

2022-02-12 17:12 UTC, ifahadone reviewed
fixed the is_array var

2022-02-13 19:52 UTC, SlavaSkvortsov commented on pytube/cipher.py
> +                return function_name
```suggestion
            is_array = '[' in function_name or ']' in function_name
            if not is_array:
                return function_name
                
            index = int(re.findall(r'\d+', function_name)[0])
            name = function_name.split('[')[0]
            pattern = r"var %s=\[(.*?)\];" % name
            regex = re.compile(pattern)
            return regex.search(js).group(1).split(',')[index]
```

2022-02-17 16:41 UTC, LonelyGuy12 commented
Amazing! please merge it soon!

2022-02-22 09:50 UTC, berke-horozal-crea approved these changes

2022-03-10 11:21 UTC, huynguyencong commented
Excellent! Please merge this one.

2022-03-29 17:36 UTC, RONNCC commented
hey @ifahadone  makes sense -- can you add a unit test for it / fix the unit tests and we can merge

2022-04-15 19:44 UTC, RONNCC commented
@glubsy  can you look at it -- also can you add a test @ifahadone  :-) -- sorry the youtube code change ups are definitely not the easiest to deal with

2022-04-15 19:53 UTC, glubsy reviewed
Looks functional, but it is essentially the same code as #1222, albeit a little simpler to read.

2022-04-15 19:55 UTC, glubsy commented
I believe this can be closed. Still, thanks for the submission @ifahadone.

2022-04-20 23:17 UTC, RONNCC commented
@glubsy  is the issue already fixed in main?

2022-04-21 19:18 UTC, glubsy commented
> @glubsy is the issue already fixed in main?

I believe so.

2022-05-08 03:27 UTC, Martouta commented
@RONNCC @glubsy Not really. It happened again and now there are many PRs open for this issue. But this PR is supposed to address it permanently (according to the title of the PR) 👍🏼

2022-05-08 09:43 UTC, glubsy commented
@Martouta it won't fix the issue permanently. 

The follow up to this issue is fixed by #1282. All the other PRs are spam and should be deleted.

2022-05-09 00:18 UTC, RONNCC commented
@Martouta  to elaborate a bit the issue is caused by Youtube changing their code - hence it can break at any time since by definition it's not a stable interface :-)

2022-05-09 00:19 UTC, closed without merging