Simplified sizeof utility
pytube/pytube pull request #126
Opened 2017-03-27 03:56 UTC by DonoA

Shortens the sizeof util to be more concise and efficient. Renames the parameter for sizeof so it does not overwrite the `bytes` function.

2017-03-27 13:18 UTC, nficano requested changes

2017-03-27 13:18 UTC, nficano commented on pytube/utils.py
> +    return str(int(byts/float(1024**power)))+' '+(sizes[power] if byts != 1 else 'byte')
please assign this to variables and use the ``.format()`` method. See https://pyformat.info/

2017-03-27 17:45 UTC, DonoA commented
Sorry about that, still fairly new to python and don't know all the cool tricks. Hope this is a bit better.

2017-03-31 02:05 UTC, nficano approved these changes
LGTM

2017-03-31 02:06 UTC, merged