Fixed error with android client version
pytube/pytube pull request #1575
Opened 2023-04-30 20:02 UTC by felipeucelli

### Fixed  error #1553, #1558, #1565, #1569, #1573

YouTube has removed support for android clients version 16.41 and below.

It is necessary to send a header indicating the origin of the request. You also need to send the sdk version.

For some reason YouTube is limiting the video url to a maximum of 30 seconds, after that time it generates a 403 error for the android client.

The`ANDROID_EMBED` client works well in some cases, however in certain videos it generates the video unavailable exception.

So far, `ANDROID_MUSIC` has proved to be the most functional.

### Functional clients

So far All clients except android are working normally.

Clients for WEB, MWEB and TV work fine, however they need to calculate the "n" throttling parameter, and `cipher.py` does not support the new javascript used.

The IOS and CREATOR clients are also working so far, but they return few flow options.

2023-05-01 02:35 UTC, huynguyencong commented
It works for me. Thank you!

2023-05-01 06:12 UTC, TXIuTnVsbA commented
It works for me. Thank you!

2023-05-01 09:03 UTC, pbxforce commented
works for me too

2023-05-01 09:06 UTC, pbxforce requested changes
I tried both files, no error for me

2023-05-01 11:38 UTC, bigbear22941 commented
works fine, except the 403 error  :(
Any other solution?

2023-05-01 12:45 UTC, felipeucelli commented
@bigbear22941 Thanks for your feedback! Could you provide me with your **pytube code**, the **link to the video where the error is occurring**, and the **complete error log**.

2023-05-01 15:22 UTC, ChaosWalker3 commented
Hello, I am new to all of this... stuff. Thanks to you, the streamingData errors have stopped, however some downloads give me an AgeRestrictedError for some reason. I have already added the use_oauth=True, allow_oauth_cache=True yet it still doesn't work. I am confused..

2023-05-01 15:47 UTC, bigbear22941 commented
> @bigbear22941 Thanks for your feedback! Could you provide me with your **pytube code**, the **link to the video where the error is occurring**, and the **complete error log**.

work...  was my fault....  perfect code !!
Thank You

2023-05-01 15:51 UTC, silmarillenschaps commented
Very nice, thanks!

Just tested the suggested changes and I am getting no more errors on videos that previously produced the KeyError.

2023-05-01 18:56 UTC, felipeucelli commented
> Hello, I am new to all of this... stuff. Thanks to you, the streamingData errors have stopped, however some downloads give me an AgeRestrictedError for some reason. I have already added the use_oauth=True, allow_oauth_cache=True yet it still doesn't work. I am confused..

@ChaosWalker3 Pytube tries to skip the age restriction using the `ANDROID_EMBED` client, but this technique is no longer working, and if you use this client as the main one in `innertube.py`, curiously it generates exceptions in videos that are not restricted (that's why `ANDROID_MUSIC` is used ). That is, pyube is not having the ability to skip the age restriction. But if you are sure that the video is not restricted, please **check the client used and provide the video link.**

2023-05-01 20:05 UTC, ChaosWalker3 commented
@felipeucelli Hello, it does not seem to be age restricted. Google says that to watch age restricted videos you must not be under 18 years old or signed out. I signed out and tested it. The video plays fine. Here is the video link: https://www.youtube.com/watch?v=KRRoQkkwuJE

The client used was ANDROID_MUSIC, I copied the contents of the innertube.py and request.py here. After having the age restricted error, I tried putting in ANDROID_EMBED before making my comment and the error still popped up. Shall I try putting in WEB, MWEB or TV? I do not understand what needing to calculate the "n" throttling parameter means so I haven't tried these yet...

2023-05-01 22:33 UTC, sukhoi47 commented
It works well for me when the (2 files) patch is applied on Pytube 12.1.3.
Thank you!

2023-05-02 02:28 UTC, Seinuve commented
Works for me as well, appreciated.

2023-05-02 03:37 UTC, felipeucelli commented
> @felipeucelli Hello, it does not seem to be age restricted. Google says that to watch age restricted videos you must not be under 18 years old or signed out. I signed out and tested it. The video plays fine. Here is the video link: https://www.youtube.com/watch?v=KRRoQkkwuJE
> 
> The client used was `ANDROID_MUSIC`, I copied the contents of the `innertube.py` and `request.py` here. After having the age restricted error, I tried putting in `ANDROID_EMBED` before making my comment and the error still popped up. Shall I try putting in `WEB`, `MWEB` or `TV`? I do not understand what needing to calculate the "n" throttling parameter means so I haven't tried these yet...

@ChaosWalker3 The link in question is working correctly on the **ANDROID_MUSIC** client.

The `WEB`, `MWEB` and `TV_EMBED`clients have a **signature cipher** that needs to be decrypted to get valid access to the url, all the logic to do this is found in **YouTube's JavaScript** (`base.js`), in most cases `cipher.py` succeeds resolve this. The "`n`" throttling parameter appears on clients to limit the download speed. To release maximum download speed, it is also necessary to decipher it, the logic used in `cipher.py` was able to do this, however YouTube updated its **JavaScript** and `cipher.py` is no longer able to decipher this parameter. That is, these clients may even work, but they will have a limited download speed rate.

2023-05-02 07:43 UTC, ChaosWalker3 commented
@felipeucelli Hello, I have fixed it! I have put `ANDROID_MUSIC` back. The reason why it didn't work was because the `bypass_age_gate` I put after initialising my `YouTube` thing gave an `AgeRestrictedError`... I thought I could just put it there as a sort of wall that would do its thing if need be.. Well, at least I learned to maybe remake my error logger function thing so it would print the whole error instead of just the name, I'll do it like Minecraft's logs and crash-reports I guess... Thank you for your time sir, and I am so sorry for wasting it.

2023-05-02 12:18 UTC, Classfied3D commented
This works for me! Thanks!

2023-05-02 22:28 UTC, DouglasRitter commented
I run pytube as part of a Lambda function, so this is not a case of being able to apply one of the solutions which uses authentication via a browser.  I applied these changes to my Lambda Layer and things are working perfectly.

2023-05-03 01:12 UTC, kof0012 commented
oh yeah

2023-05-04 00:13 UTC, Untit1ed commented
Works. Fixes #1545 as well

2023-05-05 07:43 UTC, alexerhardt commented
This seems to work flawlessly in my first tests. 

Other fixes I had seen (like only changing the client to Android) took performance hits that I'm not seeing here - it works at full speed.

Kudos to @felipeucelli for knocking it out of the park - thanks a lot.

And also, like I've said in other related Issues, my deepest sympathies to maintainers and all the people are trying to help. The Issue list has become an absolute $%&#show in the last week or so. People are posting without even adding a title to their Issues. We all have varying degrees of knowledge, and it is true that the `pytube` error message prompts the user to report an issue. But there is zero excuse if you are going to a place of interaction with other humans to dump your error log and leave, without making the minimal effort of reading open issues first.

Again thanks a lot @felipeucelli & co.

2023-05-07 11:27 UTC, felipeucelli commented
Hi @RONNCC, Pytube has been broken for about a week now. I put the fix in this PR. Feel free to check it out when you get a chance.

2023-05-07 19:02 UTC, RONNCC commented
Appreciate it @felipeucelli :-) -- sometimes hard to keep up with all the youtube breaking changes there

2023-05-07 19:19 UTC, merged

2023-05-07 19:20 UTC, RONNCC commented
@felipeucelli would you have any time to help cleanup some of the open issues / submit a large PR to fix by chance? Happy to review

2023-05-07 21:02 UTC, felipeucelli commented
> @felipeucelli would you have any time to help cleanup some of the open issues / submit a large PR to fix by chance? Happy to review

@RONNCC  I would be very happy to help.

2023-05-08 07:04 UTC, RONNCC commented
appreciate it! :-)

On Sun, May 7, 2023 at 2:02 PM Felipe Ucelli ***@***.***>
wrote:

> @felipeucelli <https://github.com/felipeucelli> would you have any time
> to help cleanup some of the open issues / submit a large PR to fix by
> chance? Happy to review
>
> @RONNCC <https://github.com/RONNCC> I would be very happy to help.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pytube/pytube/pull/1575#issuecomment-1537539858>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKAWHUYLUTZNW5ZOZNZ4N3XFAEXXANCNFSM6AAAAAAXREA5I4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>