Naive fix for Playlist returns empty list
pytube/pytube pull request #673
Opened 2020-07-03 11:33 UTC by Maelstrom6

YouTube has updated their links on playlist web pages from an href tag to a JSON object. Changed the `_video_regex` to match.

2020-07-04 07:47 UTC, Bill0412 requested changes
This works for me. The old one is truly obsolete!

2020-07-04 08:09 UTC, Maelstrom6 commented
Hi @Bill0412, I got notified that you requested changes but I can't seem to find what you requested. Is there something that I need to do?

Apologies, this is literally my first pull request :P

2020-07-09 01:36 UTC, cstuart1310 commented
Thank you so much! I've been pulling my hair out over this issue since I have no clue how pytube's backend works lol.

2020-07-13 21:12 UTC, destination05 commented
Okay, this is weird to ask, but where do I put my playlist link in this code? I've been programming for only 6 months so this code is enormous to me and I can't find where to put my playlist URL. Also, is there a line for choosing a path for where to save the files? Thank you!

2020-07-14 01:12 UTC, cstuart1310 commented
> 
> 
> Okay, this is weird to ask, but where do I put my playlist link in this code? I've been programming for only 6 months so this code is enormous to me and I can't find where to put my playlist URL. Also, is there a line for choosing a path for where to save the files? Thank you!

No worries. The code shown in this thread is a change made to the pytube library to fix a bug. Your own code then uses this library to let you interact with pytube.

To use the playlist:

`playlist = Playlist(playlistURL) ` Place this either in the main part of your program, or within the function in which it needs to be accessed. Doesn't really matter as long as you place it after
'from pytube import Playlist '

 The playlist line above will get an array of URLs, each corresponding to a video in the playlist. You can view the urls with 'print(playlist)', and reference them with 'playlist[x]', with x being the index of the URL in the array. Remember that arrays start at 0!

Feel free to message me with any more questions so we don't clog up this thread.

2020-07-17 18:46 UTC, badidrox commented
Thank you very much for the fix!

2020-07-22 12:38 UTC, tooxo commented
Implemented a complete implementation, which should replace this fix. #687

2020-07-24 01:11 UTC, Bill0412 commented
> Hi @Bill0412, I got notified that you requested changes but I can't seem to find what you requested. Is there something that I need to do?
> 
> Apologies, this is literally my first pull request :P

I meant that your pull request was really useful for me. You did an excellent job! 

Hope the owner of the repository could adopt your pull request ASAP! Currently I've got to modify the code myself before each installation.

2020-08-02 13:06 UTC, Maelstrom6 commented
Apologies for the late replies. Since I think everything seems fixed, I'll be closing this.

Thanks @tooxo for the better fix. I haven't tried it out myself but I trust that it's far more durable. Glad it's been merged.

2020-08-02 13:06 UTC, closed without merging